### PR TITLE
Use ConfirmationDialogs instead of custom buttons

### PR DESCRIPTION
**Pull request by Jummit**
This changes the order to Cancel - Accept, which is more standard. The labels of the buttons and disabling them on invalid input is not changed.

### CODE REVIEW

**Comment by SIsilicon** [comment]
The order Godot uses is OK - Cancel, so I'm sticking to that.
image
image

**Comment by Jummit** [comment]
Well, the addon could set `swap_ok_cancel` in the ProjectSettings to true.
Then it would look like this:

image

**Comment by SIsilicon** [comment]
I don't think setting a user defined variable would be a good idea. It would be best if the plugin would _read_ said variable and adjust accordingly.

**Comment by Jummit** [comment]
> I don't think setting a user defined variable would be a good idea. It would be best if the plugin would _read_ said variable and adjust accordingly.

That is the case with this PR. If the user sets `swap_ok_cancel` to true, the Create button will be the first.

**Comment by SIsilicon** [comment]
Oh I think I see the confusion!
Ok - Cancel is standard _on Windows_.
You're running Linux, are you not?

**Comment by Jummit** [comment]
> Oh I think I see the confusion!
> Ok - Cancel is standard _on Windows_.
> You're running Linux, are you not?

Yes. I think it is set automatically depending on the OS.

**Comment by SIsilicon** [comment]
Thanks! I was already deep in redoing the system, so I was afraid of merging at this point.
I implemented the features you wished to add. :)

**Pull request closed without merging**
